-- CreateEnum
CREATE TYPE "DestinationTrackingStage" AS ENUM ('ARRIVED_AT_ROTTERDAM_PORT', 'ROTTERDAM_CUSTOMS_CHECKING', 'ROTTERDAM_CUSTOMS_CLEARED', 'TO_PORT_WAREHOUSE', 'AT_PORT_WAREHOUSE', 'AWAITING_PORT_WAREHOUSE_PICKUP', 'TO_CO_ROASTER', 'AT_CO_ROASTER_WAREHOUSE', 'ROASTING_IN_PROGRESS', 'FINAL_PACKING_20KG', 'AWAITING_CO_ROASTER_PICKUP', 'TO_CLIENT', 'DESTINATION_CUSTOMS_CHECKING', 'DESTINATION_CUSTOMS_CLEARED', 'RECEIVED_BY_CLIENT');

-- AlterTable
ALTER TABLE "Shipment" ADD COLUMN     "currentStage" "DestinationTrackingStage",
ADD COLUMN     "destinationCountry" TEXT,
ADD COLUMN     "requiresDestinationCustoms" BOOLEAN NOT NULL DEFAULT false;

-- CreateIndex
CREATE INDEX "Shipment_currentStage_idx" ON "Shipment"("currentStage");
