//////////////////////////////////////////////////////
// 🪣 LOT MEDIA STORAGE — SUPABASE SERVICE
// (STORAGE-MEDIA-1 + BUYER-PROOF-1)
//
// Server-side bridge between the upload-url routes and
// Supabase Storage. Lazy: the Supabase client is only
// instantiated when the env is configured. When the
// service-role key is missing, the helper surfaces a
// clear `STORAGE_NOT_CONFIGURED` error so the route
// can return 503 and the producer UI can keep the
// URL-paste fallback alive.
//
// BUYER-PROOF-1 — two-bucket model:
//   public bucket  → PUBLIC_MARKET media (rendered as <img>)
//   private bucket → BUYER_PRIVATE + INTERNAL_ONLY media
//                    (rendered only after a signed read URL
//                    is generated by the proof endpoint).
// The pure helper resolves bucket-kind from visibility; the
// service owns the env reads + signing.
//
// ⚠️ NEVER expose Supabase env keys to the browser.
// The service-role key is server-only.
//////////////////////////////////////////////////////

import { randomUUID } from "node:crypto"
import { createClient, type SupabaseClient } from "@supabase/supabase-js"
import { prisma } from "@/src/database/prisma"
import {
  buildLotMediaStoragePath,
  buildLotMediaStorageReference,
  resolveLotMediaBucketForVisibility,
  sanitiseOriginalFileNameForMetadata,
  validateLotMediaUploadRequest,
} from "./lotMediaStorage.pure"
import {
  LOT_MEDIA_BUCKET_DEFAULT,
  LOT_MEDIA_PRIVATE_BUCKET_DEFAULT,
  LOT_MEDIA_PUBLIC_BUCKET_DEFAULT,
  LOT_MEDIA_SIGNED_READ_URL_EXPIRY_SECONDS,
  LOT_MEDIA_SIGNED_URL_EXPIRY_SECONDS,
  type LotMediaBucketConfig,
  type LotMediaSignedUploadResponse,
  type LotMediaUploadRequestInput,
  type LotMediaUploadTarget,
} from "./lotMediaStorage.types"
import type { LotMediaActor } from "./lotMedia.service"

//////////////////////////////////////////////////////
// ERROR TYPE
//////////////////////////////////////////////////////

export type LotMediaStorageErrorCode =
  | "STORAGE_NOT_CONFIGURED"
  | "MEDIA_UPLOAD_INVALID"
  | "MEDIA_UPLOAD_FORBIDDEN"
  | "MEDIA_UPLOAD_SIGNING_FAILED"
  | "MEDIA_READ_SIGNING_FAILED"
  | "OWNER_NOT_FOUND"

export class LotMediaStorageError extends Error {
  code: LotMediaStorageErrorCode
  status: number
  details?: Record<string, unknown>

  constructor(
    code: LotMediaStorageErrorCode,
    message: string,
    opts?: { status?: number; details?: Record<string, unknown> },
  ) {
    super(message)
    this.code = code
    this.name = "LotMediaStorageError"
    this.status =
      opts?.status ??
      (code === "STORAGE_NOT_CONFIGURED"
        ? 503
        : code === "MEDIA_UPLOAD_FORBIDDEN"
          ? 403
          : code === "OWNER_NOT_FOUND"
            ? 404
            : code === "MEDIA_UPLOAD_INVALID"
              ? 400
              : 500)
    if (opts?.details) this.details = opts.details
  }
}

//////////////////////////////////////////////////////
// LAZY CLIENT
//
// We resolve env at call time (not module load) so a
// later sprint can ship a different config / a feature
// flag without restarting tests. The client is cached
// once instantiated.
//
// BUYER-PROOF-1: env now carries the PUBLIC + PRIVATE
// bucket pair. We fall back to the legacy single-bucket
// env when set so STORAGE-MEDIA-1 deployments keep
// signing public uploads.
//////////////////////////////////////////////////////

type StorageEnv = {
  url: string
  serviceRoleKey: string
  buckets: LotMediaBucketConfig
}

let cachedClient: SupabaseClient | null = null
let cachedEnv: StorageEnv | null = null

function readStorageEnv(): StorageEnv | null {
  const url =
    process.env.NEXT_PUBLIC_SUPABASE_URL ||
    process.env.SUPABASE_URL ||
    ""
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY || ""
  // Legacy single-bucket env (STORAGE-MEDIA-1). When the new
  // *_PUBLIC_BUCKET var is not set we treat the legacy var as
  // the public bucket so existing deploys keep working.
  const legacyBucket = process.env.SUPABASE_LOT_MEDIA_BUCKET || ""
  const publicBucket =
    process.env.SUPABASE_LOT_MEDIA_PUBLIC_BUCKET ||
    legacyBucket ||
    LOT_MEDIA_PUBLIC_BUCKET_DEFAULT
  const privateBucket =
    process.env.SUPABASE_LOT_MEDIA_PRIVATE_BUCKET ||
    LOT_MEDIA_PRIVATE_BUCKET_DEFAULT
  if (!url || !serviceRoleKey) return null
  return {
    url,
    serviceRoleKey,
    buckets: { publicBucket, privateBucket },
  }
}

function getSupabaseClient(): { client: SupabaseClient; env: StorageEnv } {
  const env = readStorageEnv()
  if (!env) {
    throw new LotMediaStorageError(
      "STORAGE_NOT_CONFIGURED",
      "Image uploads aren't configured on this environment yet. You can still paste an image URL.",
    )
  }
  if (cachedClient && cachedEnv && cachedEnv.url === env.url) {
    return { client: cachedClient, env }
  }
  cachedClient = createClient(env.url, env.serviceRoleKey, {
    auth: {
      // Service-role client; never refresh sessions.
      autoRefreshToken: false,
      persistSession: false,
    },
  })
  cachedEnv = env
  return { client: cachedClient, env }
}

// Exported for the proof-media route layer so it can
// surface a clean 503 without trying to sign anything.
export function isLotMediaStorageConfigured(): boolean {
  return readStorageEnv() !== null
}

// Surfaced so callers (proof endpoint) can confirm the
// configured private bucket matches references stored
// in the database before signing.
export function getLotMediaBucketConfig(): LotMediaBucketConfig {
  return getSupabaseClient().env.buckets
}

// Legacy alias retained for STORAGE-MEDIA-1 fixtures.
export { LOT_MEDIA_BUCKET_DEFAULT }

//////////////////////////////////////////////////////
// OWNERSHIP CHECKS
//
// Mirror the contract used by lotMedia.service —
// producer can only sign uploads for their own farms /
// lots; partner / admin bypass. We re-run the check
// here (vs. trusting the route) so the storage service
// is safe to call from anywhere.
//////////////////////////////////////////////////////

async function ensureFarmOwnership(
  farmId: string,
  actor: LotMediaActor,
): Promise<void> {
  const farm = await prisma.farm.findUnique({
    where: { id: farmId },
    select: { id: true, producer: { select: { userId: true } } },
  })
  if (!farm) {
    throw new LotMediaStorageError("OWNER_NOT_FOUND", "Farm not found.")
  }
  if (actor.role === "PRODUCER" && farm.producer?.userId !== actor.userId) {
    throw new LotMediaStorageError(
      "MEDIA_UPLOAD_FORBIDDEN",
      "You can only upload media on farms you own.",
    )
  }
}

async function ensureLotOwnership(
  greenLotId: string,
  actor: LotMediaActor,
): Promise<void> {
  const lot = await prisma.greenLot.findUnique({
    where: { id: greenLotId },
    select: {
      id: true,
      farm: { select: { producer: { select: { userId: true } } } },
    },
  })
  if (!lot) {
    throw new LotMediaStorageError("OWNER_NOT_FOUND", "Green lot not found.")
  }
  if (
    actor.role === "PRODUCER" &&
    lot.farm?.producer?.userId !== actor.userId
  ) {
    throw new LotMediaStorageError(
      "MEDIA_UPLOAD_FORBIDDEN",
      "You can only upload media on lots you own.",
    )
  }
}

//////////////////////////////////////////////////////
// CORE: createLotMediaSignedUpload
//
// 1. Validate the upload request via the pure helper.
// 2. Confirm the actor can write to the owner.
// 3. Resolve bucket from visibility (PUBLIC_MARKET vs
//    BUYER_PRIVATE / INTERNAL_ONLY).
// 4. Build a safe storage path.
// 5. Ask Supabase Storage for a signed upload URL.
// 6. Return the URL + token + storage reference. The
//    publicUrl is set only for PUBLIC uploads; private
//    rows persist the storageReference instead.
//
// We deliberately do NOT create the FarmMedia /
// GreenLotMedia row here. The browser POSTs to the
// existing create endpoint with the appropriate `url`
// (publicUrl or storageReference) after the upload
// completes, so the same single-primary transaction +
// ownership checks fire.
//////////////////////////////////////////////////////

export type CreateLotMediaSignedUploadInput = {
  actor: LotMediaActor
  target: LotMediaUploadTarget
  ownerId: string
  body: LotMediaUploadRequestInput
}

export async function createLotMediaSignedUpload(
  input: CreateLotMediaSignedUploadInput,
): Promise<LotMediaSignedUploadResponse> {

  // ─── VALIDATE ─────────────────────────────────────
  const validation = validateLotMediaUploadRequest(input.body)
  if (!validation.ok) {
    throw new LotMediaStorageError(
      "MEDIA_UPLOAD_INVALID",
      validation.error.message,
      { details: { code: validation.error.code } },
    )
  }
  const req = validation.input

  // ─── OWNERSHIP ────────────────────────────────────
  if (input.target === "FARM") {
    await ensureFarmOwnership(input.ownerId, input.actor)
  } else {
    await ensureLotOwnership(input.ownerId, input.actor)
  }

  // ─── ENV / CLIENT ─────────────────────────────────
  const { client, env } = getSupabaseClient()

  // ─── BUCKET RESOLUTION ────────────────────────────
  const bucketResolution = resolveLotMediaBucketForVisibility(
    req.visibility,
    env.buckets,
  )
  const targetBucket = bucketResolution.bucket

  // ─── STORAGE PATH ─────────────────────────────────
  const storagePath = buildLotMediaStoragePath({
    target: input.target,
    ownerId: input.ownerId,
    role: req.role,
    contentType: req.contentType,
    uuid: randomUUID(),
  })

  // ─── SIGN UPLOAD ──────────────────────────────────
  let signedUrl: string
  let token: string | undefined
  try {
    const { data, error } = await client.storage
      .from(targetBucket)
      .createSignedUploadUrl(storagePath)
    if (error || !data?.signedUrl) {
      throw new LotMediaStorageError(
        "MEDIA_UPLOAD_SIGNING_FAILED",
        "We couldn't prepare the upload. Please try again in a moment.",
        { details: error ? { supabaseError: error.message } : undefined },
      )
    }
    signedUrl = data.signedUrl
    token = (data as { token?: string }).token
  } catch (err) {
    if (err instanceof LotMediaStorageError) throw err
    throw new LotMediaStorageError(
      "MEDIA_UPLOAD_SIGNING_FAILED",
      "We couldn't prepare the upload.",
      { details: { error: err instanceof Error ? err.message : String(err) } },
    )
  }

  // ─── REFERENCE + PUBLIC URL ───────────────────────
  const storageReference = buildLotMediaStorageReference({
    bucket: targetBucket,
    storagePath,
  })

  // Public URL only for PUBLIC bucket uploads. Private
  // rows must be read through createLotMediaSignedReadUrl.
  let publicUrl: string | null = null
  if (bucketResolution.kind === "PUBLIC") {
    const { data: publicData } = client.storage
      .from(targetBucket)
      .getPublicUrl(storagePath)
    publicUrl = publicData?.publicUrl ?? null
  }

  return {
    uploadUrl: signedUrl,
    token,
    method: "PUT",
    bucket: targetBucket,
    bucketKind: bucketResolution.kind,
    storagePath,
    storageReference,
    publicUrl,
    expiresInSeconds: LOT_MEDIA_SIGNED_URL_EXPIRY_SECONDS,
    mediaDefaults: {
      role: req.role,
      source: req.source,
      visibility: req.visibility,
    },
  }
}

//////////////////////////////////////////////////////
// CORE: createLotMediaSignedReadUrl
//
// Signs a short-lived read URL for a private storage
// reference. Used exclusively by the proof-media
// endpoint after it has confirmed the caller is
// authorised to view the underlying contract/lot.
//
// Callers MUST run their own audience filter first —
// this helper trusts its input and only handles the
// signing mechanics.
//////////////////////////////////////////////////////

export type CreateLotMediaSignedReadUrlInput = {
  bucket: string
  storagePath: string
  expiresInSeconds?: number
}

export type LotMediaSignedReadUrlResult = {
  bucket: string
  storagePath: string
  signedUrl: string
  expiresInSeconds: number
}

export async function createLotMediaSignedReadUrl(
  input: CreateLotMediaSignedReadUrlInput,
): Promise<LotMediaSignedReadUrlResult> {
  const { client } = getSupabaseClient()
  const expiresIn =
    typeof input.expiresInSeconds === "number" &&
    Number.isFinite(input.expiresInSeconds) &&
    input.expiresInSeconds > 0
      ? Math.floor(input.expiresInSeconds)
      : LOT_MEDIA_SIGNED_READ_URL_EXPIRY_SECONDS

  try {
    const { data, error } = await client.storage
      .from(input.bucket)
      .createSignedUrl(input.storagePath, expiresIn)
    if (error || !data?.signedUrl) {
      throw new LotMediaStorageError(
        "MEDIA_READ_SIGNING_FAILED",
        "We couldn't prepare the proof image for viewing.",
        {
          details: {
            bucket: input.bucket,
            supabaseError: error?.message,
          },
        },
      )
    }
    return {
      bucket: input.bucket,
      storagePath: input.storagePath,
      signedUrl: data.signedUrl,
      expiresInSeconds: expiresIn,
    }
  } catch (err) {
    if (err instanceof LotMediaStorageError) throw err
    throw new LotMediaStorageError(
      "MEDIA_READ_SIGNING_FAILED",
      "We couldn't prepare the proof image for viewing.",
      { details: { error: err instanceof Error ? err.message : String(err) } },
    )
  }
}

// Surfaced so route layers can attach the sanitised filename to
// the create-media payload's `metadata` later if product wants it.
export { sanitiseOriginalFileNameForMetadata }
